server:
  port: 8080

spring:
  datasource:
    shard1:
      jdbc-url: ${NEON_SHARD1_URL}
      username: ${NEON_DB_USER}
      password: ${NEON_DB_PASS}
      driver-class-name: org.postgresql.Driver
    shard2:
      jdbc-url: ${NEON_SHARD2_URL}
      username: ${NEON_DB_USER}
      password: ${NEON_DB_PASS}
      driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
        
  data:
    redis:
      url: ${UPSTASH_REDIS_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics